Repository IOSD/IOSD-UIETKUK-HacktoberFest-Meetup-2019, pull requests merged in 2019-10, with the labels that each got.

#89 Create Quicksort_78914802717.cpp
  Intermediate/78914802717.cpp
  Intermediate/Quicksort_78914802717.cpp
Labels: Hacktoberfest, Intermediate

#90 Create bfsTraversal.java
  Advanced/bfsTraversal.java
  Intermediate/Bubble_Sorting.java
  Intermediate/Quicksort.java
  Intermediate/mergsort.java
Labels: Hacktoberfest, Intermediate

#91 QuickSort_tarun2k_085.java
  Beginner/Odd&Even_tarun2k_085.java
  Beginner/OddEven_tarun2k_085.java
  Beginner/Palindrome_tarun2k_085.java
  Intermediate/BinarySearch_tarun2k_085.java
  Intermediate/Binarysearch_tarun2k_085.java
  Intermediate/QuickSort_tarun2k_085.java
Labels: Hacktoberfest

#93 Bubblesort_251802053.cpp
  Intermediate/Binarysearch_251802053.cpp
  Intermediate/Bubblesort_251802053.cpp
  Intermediate/FlipTheBitsOfNo_251802053.cpp
  Intermediate/Quicksort_251802053.cpp
Labels: Hacktoberfest, Intermediate

#94 Create BreadthFirstSearch.cpp
  Advanced/BreadthFirstSearch.cpp
Labels: Hacktoberfest, Intermediate

#96 Detect and remove loop from lisnked list c++ prog
  Advanced/DetectAndRemoveLoopLinkedList.cpp
Labels: Advanced, Hacktoberfest

#247 age_check25.py
  Beginner/age_check25.py
Labels: beginner

#208 binary search in golang
  binary_search.go
Labels: Intermediate

#223 I have made some files in c++ on sorting algorithms (which are good applications for learning basic concepts of c++).
  sort it out in c++/bubble sort.cpp
Labels: Intermediate

#98 quicksort_051.c
  Intermediate/quicksort_051.c
Labels: Hacktoberfest

#106 odd-even.cpp
  Beginner/age-check.cpp
  Beginner/odd-even.cpp
  age.cpp
Labels: Hacktoberfest

#107 agecheck.cpp
  Beginner/agecheck.cpp
Labels: Hacktoberfest

#108 odd_even.cpp
  Beginner/odd_even.cpp
Labels: Hacktoberfest

#109 Quick_sort_01876802717.java
  Beginner/Age_checker_01876802717.java
  Intermediate/Quick_sort_01876802717.java
Labels: Hacktoberfest

#111 QuickSort178102.cpp
  Intermediate/BinarySearch178102.cpp
  Intermediate/Bubblesort178102.cpp
  Intermediate/QuickSort178102.cpp
  Intermediate/flipthebits178102.cpp
Labels: Hacktoberfest

#112 Bubble_sort24.java
  Intermediate/Bubble_sort24.java
Labels: Hacktoberfest

#113 Binary_search24.java
  Intermediate/Binary_search24.java
Labels: Hacktoberfest

#114 QUICKSORT_03415603117.cpp
  Intermediate/QUICKSORT_03415603117.cpp
Labels: Hacktoberfest

#118 OddOrEven_251701133.java
  Beginner/Age_251701133.java
  Beginner/OddOrEven_251701133.java
Labels: Hacktoberfest

#119 pattern_53203266
  Beginner/pattern_53203266
  Intermediate/merge_sort.c
Labels: Hacktoberfest

#120 bubblesort.c
  Intermediate/bubblesort.c
Labels: Hacktoberfest

#121 fibonacci_44613302717.cpp
  BubbleSort_44613302717.cpp
  breadthFirstSearch.cpp
  fibonacci_44613302717.cpp
Labels: Hacktoberfest

#123 oddeven2303.py
  Beginner/ageadultteencheck.py
  Beginner/fibanocii_sequence.py
  binary_search2303.py
  bubblesort2303.py
  oddeven2303.py
  palindrome_check.py
Labels: Hacktoberfest

#124 bfs_2k.cpp
  Advanced/bfs_2k.cpp
  Advanced/dfs_2k.cpp
  Intermediate/quick_sort2k.cpp
Labels: Hacktoberfest

#127 Bubblesort_1234.java
  Beginner/InputAge_1234.java
  Beginner/Input_Age_1234.java
  Beginner/OddorNot.java
  Intermediate/Bubblesort_1234.java
  binary_search1234.java
  binary_search_1234.java
Labels: Hacktoberfest

#128 quicksort_goyal.aman.py
  Intermediate/bubblesort_goyal_aman.py
Labels: Hacktoberfest

#129 bubblesort12800.cpp
  Beginner/StringPalindrome12800
  Intermediate/bubblesort12800.cpp
Labels: Hacktoberfest

#130 Create Mergesort.cpp
  Beginner/Fibbonaci2712.cpp
  Intermediate/Mergesort.cpp
Labels: Hacktoberfest

#131 oddOrNot.py
  Beginner/ageCheck.py
  Beginner/fibonacciSequence.py
  Beginner/oddOrNot.py
  Beginner/palindromeCheck.py
Labels: Hacktoberfest

#132 oddfinder_02320803117
  Beginner/Age_02320803117.cpp
  Beginner/odd_finder.py
Labels: Hacktoberfest

#134 bubble_sort.py
  Intermediate/bubble_sort.py
Labels: Hacktoberfest

#135 bfs.py
  Advanced/bfs.py
Labels: Hacktoberfest

#136 Palindrome_1234.java
  Beginner/Palindrome_1234.java
Labels: Hacktoberfest

#103 solution to bfs added
  Advanced/breadth_1st_search.cpp
  Advanced/detectandbreakloopinlinkedlist.cpp
  Intermediate/flipbits.cpp
Labels: Hacktoberfest

#99 Create FlipTheBits.cpp
  Advanced/IrisDecisionTree.py
  Intermediate/FlipTheBits.cpp
Labels: Hacktoberfest

#138 Input_age.java
  Beginner/Input_age.java
Labels: Hacktoberfest

#141 Check_odd_or_not.cpp
  BFS.cpp
  Beginner/Check_odd_or_not.cpp
  Beginner/age_check.cpp
Labels: Hacktoberfest

#145 SquarePattern.cpp
  Beginner/SquarePattern.cpp
Labels: Hacktoberfest

#148 odd_even by SirZOMBiE
  Beginner/age.py
  Beginner/odd_or_even.py
Labels: Hacktoberfest

#150 recursive bubble sort
  Intermediate/Recursive_Bubble_Sort.cpp
Labels: Hacktoberfest

#156 depth_first_search.cpp
  Advanced/depth_first_search.cpp
Labels: Hacktoberfest

#157 binary_search.cpp
  binary_search.cpp
Labels: Hacktoberfest

#161 Fibonacci_number_generator
  Beginner/Fibonacci_numbers_generator.py
Labels: Hacktoberfest

#163 SolutionByJagmeet_CheckEvenOdd.py
  Beginner/SolutionByJagmeet_evenOdd.py
Labels: Hacktoberfest

#168 selectionSort.java
  Intermediate/selectionSort.java
Labels: Hacktoberfest

#169 python implementation of binary search
  Intermediate/BINARY SEARCH.PY
Labels: Hacktoberfest

#170 Added adult-check.py
  Beginner/adult-check.py
Labels: Hacktoberfest

#173 [Intermediate ] Bubble Sort [Java]
  Intermediate/bubblesort.java
Labels: Hacktoberfest

#174 [Advance] Travelling Salesman Problem [Java]
  Advanced/TravellingSalesmanProblem.java
Labels: Hacktoberfest

#176 Bellman_Ford_algorithm
  Advanced/Bellman_Ford_algorithm.cpp
Labels: Hacktoberfest

#177 add Fibonacci_Sequence.py
  Beginner/Fibonacci_Sequence.py
  Beginner/Odd_or_Not.py
Labels: Hacktoberfest

#178 BubbleSort.cpp
  Beginner/CheckEvenOdd
  Intermediate/Binary_Search.cpp
  Intermediate/BubbleSort.cpp
  Intermediate/Quick_sort
Labels: Hacktoberfest

#180 Flip the Bits
  Intermediate/Bit_Flip_python.py
Labels: Hacktoberfest

#182 oddOrNot_17251A05H5.c
  Beginner/CheckAge_17251A05H5.c
  Beginner/Fibanocci_17251A05H5.c
  Beginner/PalindromeOrNot_17251A05H5.cpp
  Beginner/oddOrNot_17251A05H5.c
  Intermediate/BinarySearch_17251A05H5.java
Labels: Hacktoberfest

#183 BFS-01876802717.java
  Advanced/BFS_01876802717.java
Labels: Hacktoberfest

#185 matrix_operations.c
  Advanced/PrimsAlgo.c
  Beginner/swap.c
  Intermediate/matrix.c
  Intermediate/matrix_operations.c
Labels: Hacktoberfest

#187 EvenOdd.cpp
  Beginner/EvenOdd.cpp
Labels: Hacktoberfest

#189 Binary_search.py
  Beginner/odd_even
  Intermediate/Binary_search.py
  Intermediate/bubble_sort
Labels: Hacktoberfest

#190 optimized bubble sort
  bubble_sort.cpp
Labels: Hacktoberfest

#193 FlippingTheBitsProgram.py
  Intermediate/FlippingTheBitsProgram.py
Labels: Hacktoberfest

#194 Create even_or_odd.c
  Beginner/AGE_CHECK.c
  Beginner/even_or_odd.c
Labels: Hacktoberfest

#195 create prims_algo.c
  Advanced/prims_algo.c
Labels: Hacktoberfest

#175 [Intermediate] Quick Sort [Java]
  Intermediate/QuickSort2603.java
Labels: Hacktoberfest

#95 TravellingSalesman.cpp
  Advanced/TravellingSalesmanProblem.cpp
Labels: Advanced, Hacktoberfest

#202 Quicksort_4D7.py
  Beginner/Firstnode_4.py
  Intermediate/Quicksort_4D7.py
Labels: Hacktoberfest

#204 palindrome.cpp
  Beginner/palindrome_444.cpp
Labels: Hacktoberfest

#205 facorialcode.cpp
  Beginner/factorialcode.cpp
Labels: Hacktoberfest

#206 palindrome in golang
  palindrome.go
Labels: Hacktoberfest

#207 selection sort in golang
  selectionsort.go
Labels: Hacktoberfest

#209 create buublesort.js
  Beginner/bubblesort.js
Labels: Hacktoberfest

#220 Create palindromehj.c
  Beginner/palindromehj.c
Labels: Hacktoberfest

#221 Create flipbitshj.c
  Intermediate/flipbitshj.c
Labels: Hacktoberfest

#222 Create binarysearchhj.c
  Intermediate/binarysearchhj.c
Labels: Hacktoberfest

#224 binarySearch.cpp
  Intermediate/binarySearch.cpp
Labels: Hacktoberfest

#225 Beginner Commit
  Advanced/BFS(Graphs).cpp
  Advanced/DFS(GRAPHS).cpp
  Beginner/Age.cpp
  Beginner/Even_&_odd- Copy.cpp
  Beginner/fibonacci.cpp
  Beginner/palin.cpp
Labels: Hacktoberfest

#226 Implementation Of DFS Algorithm in Python.
  Advanced/DepthFirstSearch(DFS).py
Labels: Hacktoberfest

#227 Create BitsFlip.cpp
  Intermediate/BitsFlip.cpp
Labels: Hacktoberfest
